@startuml
top to bottom direction
skinparam packageStyle rect

actor Cadabra
actor Bolod
actor SaleBean
actor dashboard

Cadabra --> Bolod
Cadabra --> SaleBean
Cadabra --> dashboard

@enduml

'-------------------- New Page --------------------

@startuml
start
:login/admin-login;

if (Admin logs in?) then (yes)
  :Go to admin dashboard project;
else if(User logs in?) then (yes)
    :Go to user home page with signout option;
else
  :show B Cadabra Home page without login;
endif
stop
@enduml

'-------------------- New Page --------------------
@startuml

start
:Admin Login;
if (SuperAdmin logs in?) then (yes)
  :Go to admin dashboard project with all access;
  if (SuperAdmin) then (yes)
    :show default dashboard with all access;
  else
    if (SaleAdmin) then (yes)
      :show dashboard with limited access for SaleAdmin;
      if (SaleManager) then (yes)
        :show dashboard with limited access for SaleManager;
      else
        :login again;
      endif
    else
      if (ProductAdmin) then (yes)
        :show dashboard with limited access for ProductAdmin;
        if (Product) then (yes)
          :show product dashboard;
        else
          :login again;
        endif
      else
        :login again;
      endif
    endif
  endif
else
  :show B Cadabra Home page without login;
endif

stop
@enduml


'-------------------- New Page --------------------
@startuml

Start
:admin is logged in;

if(Admin login in) then(yes)
  :Go the Dashboard;
    if(Blog) then(yes)
    :Go to Blog;


@enduml


'-------------------- New Page --------------------
